### PR TITLE
.length shouldn't change on duplicate puts and removeItem of non-existent keys

### PR DESCRIPTION
**Pull request by mvayngrib**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Failing due to lint:

    tests/webrunner.js: line 51, col 12, 'onReady' was used before it was defined.

**Comment by nolanlawson** [comment]
Also this lint has nothing to do with this PR; not sure why it's suddenly complaining?

**Comment by nolanlawson** [comment]
Opened #3 to fix the linting issue.

**Comment by nolanlawson** [comment]
ping @gr2m If you merge this and #3 it should pass.

**Comment by gr2m** [comment]
ooops I'm so sorry, I didn't watch the repo, I'll have a look asap

**Comment by nolanlawson** [comment]
No prob!

**Comment by gr2m** [comment]
I’ve another PR ready that will merge this in, but I updated Travis & added semantic-release, now Travis is stuck and I dunno why :/ https://travis-ci.org/gr2m/localstorage-memory

Hope it picks it up eventually. I changed from the legacy system to the container based one, might be the reason why it takes longer to pick up

**Comment by gr2m** [comment]
released https://github.com/gr2m/localstorage-memory/releases/tag/v1.0.2

**Comment by nolanlawson** [comment]
Woot!

**Pull request closed without merging**
